services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    image: pgrouting/pgrouting:17-3.5-3.7
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
      - db-data:/var/lib/postgresql/data
    environment:
      # Include both PG_ and POSTGRES_ variants to support psql and postgresql server
      - PGHOST=localhost
      - PGPORT=5432
      - PGUSER=chillstreets
      - PGPASSWORD=password
      - PGDATABASE=chillstreets
      - POSTGRES_USER=chillstreets
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chillstreets

volumes:
  db-data:
