alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: chillstreets-frontend
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: chillstreets
region: nyc
static_sites:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: kalilsn/chillstreets
  name: chillstreets-frontend
  output_dir: dist
  source_dir: frontend
