alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
  version: "17"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: chillstreets-frontend
    match:
      authority:
        exact: ""
      path:
        prefix: /
  - component:
      name: chillstreets-backend
      preserve_path_prefix: true
    match:
      authority:
        exact: ""
      path:
        prefix: /api
jobs:
- dockerfile_path: backend/Dockerfile
  envs:
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  github:
    branch: main
    deploy_on_push: true
    repo: kalilsn/chillstreets
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  kind: PRE_DEPLOY
  name: chillstreets-migrations
  run_command: uv run manage.py migrate
  source_dir: backend
name: chillstreets
region: nyc
services:
- dockerfile_path: backend/Dockerfile
  envs:
  - key: POSTGRES_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: '*'
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:8m69EkLq5ATQMMqRdfavrG71LnGUpUqa:6T1yx8A6SK2Age45pwjnNpk2Y3sloj6eozrE6Rc3d0Nlo+jwPA7ZK/qP8/CZm6DIMyjVN3dn9HTuq7tu4GYfSRdg]
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  github:
    branch: main
    deploy_on_push: true
    repo: kalilsn/chillstreets
  health_check:
    http_path: /api/health
  http_port: 443
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: chillstreets-backend
  run_command: uv run manage.py runserver 0.0.0.0:443
  source_dir: backend
static_sites:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: kalilsn/chillstreets
  name: chillstreets-frontend
  output_dir: dist
  source_dir: frontend
