// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetRoutesData, GetRoutesResponses, SaveRouteChangesData, SaveRouteChangesResponses, HealthData, HealthResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Routes
 */
export const getRoutes = <ThrowOnError extends boolean = false>(options?: Options<GetRoutesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRoutesResponses, unknown, ThrowOnError>({
        url: '/api/routes',
        ...options
    });
};

/**
 * Save
 */
export const saveRouteChanges = <ThrowOnError extends boolean = false>(options: Options<SaveRouteChangesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SaveRouteChangesResponses, unknown, ThrowOnError>({
        url: '/api/routes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthResponses, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};