// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ChillstreetsUrlsSnapData, ChillstreetsUrlsSnapResponses, ChillstreetsUrlsHealthData, ChillstreetsUrlsHealthResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Snap
 */
export const chillstreetsUrlsSnap = <ThrowOnError extends boolean = false>(options: Options<ChillstreetsUrlsSnapData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ChillstreetsUrlsSnapResponses, unknown, ThrowOnError>({
        url: '/api/snap',
        ...options
    });
};

/**
 * Health
 */
export const chillstreetsUrlsHealth = <ThrowOnError extends boolean = false>(options?: Options<ChillstreetsUrlsHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ChillstreetsUrlsHealthResponses, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};