// This file is auto-generated by @hey-api/openapi-ts

/**
 * RouteChanges
 */
export type RouteChanges = {
    /**
     * Updated
     */
    updated: {
        [key: string]: string;
    };
    /**
     * Deleted
     */
    deleted: Array<string>;
};

/**
 * Route
 */
export type Route = {
    /**
     * Id
     */
    id: string;
    /**
     * Geometry
     */
    geometry: string;
};

export type GetRoutesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/routes';
};

export type GetRoutesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<Route>;
};

export type GetRoutesResponse = GetRoutesResponses[keyof GetRoutesResponses];

export type SaveRouteChangesData = {
    body: RouteChanges;
    path?: never;
    query?: never;
    url: '/api/routes';
};

export type SaveRouteChangesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRouteOsmIntersectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/route-osm-intersections';
};

export type GetRouteOsmIntersectionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWaysTileData = {
    body?: never;
    path: {
        /**
         * Z
         */
        z: number;
        /**
         * X
         */
        x: number;
        /**
         * Y
         */
        y: number;
    };
    query?: never;
    url: '/api/ways/{z}/{x}/{y}';
};

export type GetWaysTileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};