// This file is auto-generated by @hey-api/openapi-ts

export type ChillstreetsUrlsSnapData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Source
         */
        source: string;
        /**
         * Dest
         */
        dest: string;
    };
    url: '/api/snap';
};

export type ChillstreetsUrlsSnapResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ChillstreetsUrlsHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type ChillstreetsUrlsHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};