# Generated by Django 5.2.4 on 2025-07-10 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillstreets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('original_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('snapped_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'user_routes',
                'managed': True,
            },
        ),
    ]
