# Generated by Django 5.2.4 on 2025-07-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillstreets', '0002_userroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroute',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
